"""empty message

Revision ID: 8564cef3027e
Revises: a629485eb91b
Create Date: 2023-05-31 19:49:55.283588

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8564cef3027e'
down_revision = 'a629485eb91b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.add_column(sa.Column('newsdate', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('label', sa.Boolean(), nullable=True))
        batch_op.drop_column('description_en')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description_en', mysql.TEXT(), nullable=True))
        batch_op.drop_column('label')
        batch_op.drop_column('newsdate')

    # ### end Alembic commands ###
